name       : pipes-sh
version    : 1.2.0
release    : 1
source     :
    - https://github.com/pipeseroni/pipes.sh/archive/v1.2.0.tar.gz : cb1901ece366205698c8572ef897743d1fb8e3e51abd42d3946e7e30f0831dec
license    : MIT
component  : desktop
summary    : Animated pipes terminal screensaver.
description: |
    Animated pipes terminal screensaver.
install    : |
    %make_install PREFIX=/usr
